name: bitcoin-price-behavior
channels:
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - python=3.13
  - scipy
  - seaborn
  - statsmodels
  - yfinance
  - pip:
    - arch==7.2.0
